server:
  port: 9003
  
  
Eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      
spring:
  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
        - id: COLLEGE-SERVICE
          uri: lb://COLLEGE-SERVICE
          predicates:
            - Path=/college/**
          
